name: PandeLoot
main: net.seyarada.pandeloot.PandeLoot
version: 2.0.0
authors:
  - FluffyWorld (Fork of PandeLoot)
api-version: 1.17
softdepend: [MythicMobs, MMOItems]
commands:
  pandeloot:
    description: Base command for PandeLoot
    usage: /pandeloot
    permission: pandeloot.use
    aliases:
      - ploot